### ISSUE TITLE
Can't find model 'en'. It looks like you're trying to load a model from a shortcut, which is obsolete as of spaCy v3.0. To load the model, use its full name instead

### ISSUE THREAD

**Issue by Imzachjohnson** [hetpandya/textgenie#2]
Looks like this may have changed in a new version of spacy. Created a pull request that might fix the issue. 

The model can be downloaded via: python -m spacy download en_core_web_sm

**Comment by hetpandya** [comment]
Hi @Imzachjohnson , thanks for pointing out this issue! I'll merge the pull with mine!
