### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by dhern023** [hetpandya/textgenie#5]
This repo and https://github.com/DanManN/pass2act/blob/master/pass2act.py contain the same exact code, and they're using Apache 2.0.

**Comment by hetpandya** [comment]
Hi @dhern023, it seems that you couldn't find the credits in the references section of the documentation. You can find it here https://github.com/hetpandya/textgenie#references

**Comment by dhern023** [comment]
You have to include a copy of the Apache License.

**Comment by hetpandya** [comment]
@dhern023 The credits to the original author were already mentioned in the function being used under [grammar_utils.py](https://github.com/hetpandya/textgenie/blob/6d3e66cbe39a7977aca1f42dc52a371dc546d12b/textgenie/grammar_utils.py#L36). Nevertheless, I've attached the licence name in the same file as well. Thanks for mentioning!
